baseURL: https://frederikbjorn.com
languageCode: en-us
title: Frederik Bjorn
theme: hugo-PaperMod
paginate: 5

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: Posts
      url: /posts
      weight: 1
    - name: About
      url: /about
      weight: 3
    - name: Music
      url: /music
      weight: 2
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  homeInfoParams:
    enabled: true
    Title: "frederikbjorn.com"
    Content: Hi, I'm Frederik Bjørn. <br> This is a small website used for portfolie and a few toturials. <br> Underneath are the different toturial posts. Cheers.



  socialIcons:
    - name: soundcloud
      url: https://soundcloud.com/frederikbjoern
    - name: github
      url: https://github.com/FrederikBjorn
    - name: linkedin
      url: https://www.linkedin.com/in/frederik-bj%C3%B8rn-6339b5170
    - name: bandcamp
      url: https://frederikbjorn.bandcamp.com/

