baseURL: https://frederikbjorn.com
languageCode: en-us
title: Frederik Bjorn
theme: hugo-PaperMod
paginate: 5

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: Posts
      url: /posts
      weight: 1
    - name: About
      url: /about
      weight: 3
    - name: Music
      url: /music
      weight: 2
markup:
  goldmark:
    renderer:
      unsafe: true

  defaultTheme: light


params:
  profileMode:
    enabled: true
    Title: "frederikbjorn.com"
    Content: Game Audio, music and different recipes for porridge.
    buttons:
            - name: About
            url: "/about"
            - name: Posts
            url: "/posts"
            - name: Music
            url: "/music"


  socialIcons:
    - name: soundcloud
      url: https://soundcloud.com/frederikbjoern
    - name: github
      url: https://github.com/FrederikBjorn
    - name: linkedin
      url: https://www.linkedin.com/in/frederik-bj%C3%B8rn-6339b5170
    - name: bandcamp
      url: https://frederikbjorn.bandcamp.com/

