baseURL: https://frederikbjorn.com
languageCode: en-us
title: Frederik Bjorn
theme: hugo-PaperMod
paginate: 6

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: Guides
      url: /guides
      weight: 2
    - name: About
      url: /about
      weight: 4
    - name: Music
      url: /music
      weight: 3
    - name: Portfolio
      url: /portfolio
      weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true





params:
  homeInfoParams:
    enabled: true
    Title: 
    Content: <a style="text-decoration:none;font-family:courier new;font-size:14px;text-decoration:none;">  Hi, I'm Frederik Bjørn. <br> This is a small website used for my portfolio containing my portfolio, music, sound design work and a few guides to game audio.


  socialIcons:
    - name: soundcloud
      url: https://soundcloud.com/frederikbjoern
    - name: github
      url: https://github.com/FrederikBjorn
    - name: linkedin
      url: https://www.linkedin.com/in/frederik-bj%C3%B8rn-6339b5170
    - name: bandcamp
      url: https://frederikbjorn.bandcamp.com/

