baseURL: https://frederikbjorn.com
languageCode: en-us
title: Frederik Bjorn
theme: origin-hugo-theme-master
copyright: "2022, Frederik Bjørn"
paginate: 4



minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: Contact
      url: /contact
      weight: 3
      
    - name: Home
      url: /
      weight: 1

      

markup:
  goldmark:
    renderer:
      unsafe: true





params:
  featured: true


  homeInfoParams:
    enabled: true
    Title: 
    Content: 



