baseURL: https://frederikbjorn.com
languageCode: en-us
title: Frederik Bjorn
theme: origin-hugo-theme-master
copyright: "2022, Frederik Bjørn"
paginate: 10



minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: Contact
      url: /contact
      weight: 3
      
    - name: Home
      url: /
      weight: 1

      

markup:
  goldmark:
    renderer:
      unsafe: true





params:
  featured: true


  homeInfoParams:
    enabled: true
    Title: 
    Content: 


  socialIcons:
    - name: soundcloud
      url: https://soundcloud.com/frederikbjoern
    - name: github
      url: https://github.com/FrederikBjorn
    - name: linkedin
      url: https://www.linkedin.com/in/frederik-bj%C3%B8rn-6339b5170
    - name: bandcamp
      url: https://frederikbjorn.bandcamp.com/

