baseURL: https://frederikbjorn.com
languageCode: en-us
title: Frederik Bjorn
theme: hugo-PaperMod
paginate: 5

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: Guides
      url: /guides
      weight: 1
    - name: About
      url: /about
      weight: 3
    - name: Music
      url: /music
      weight: 2
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  homeInfoParams:
    enabled: true
    Title: 
    Content: <a style="text-decoration:none;font-family:courier new;font-size:14px;text-decoration:none;">  Hi, I'm Frederik Bjørn. <br> This is a small website used for my portfolio containing my music, sound design work and a few guides to game audio. <br><br> <a href="https://frederikbjorn.com/guides/"><em><strong>Please check out my Guides</strong></em></a>


  socialIcons:
    - name: soundcloud
      url: https://soundcloud.com/frederikbjoern
    - name: github
      url: https://github.com/FrederikBjorn
    - name: linkedin
      url: https://www.linkedin.com/in/frederik-bj%C3%B8rn-6339b5170
    - name: bandcamp
      url: https://frederikbjorn.bandcamp.com/

